id: IB00BA97C
legacy_id: P006899
ocr_import_info:
  bdrc_scan_id: W22248
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:16:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:04:35.654564+00:00'
last_modified: 2022-09-02 05:04:50.065302
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22248
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22248
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་རྣམ་བཤད་གཞུང་དོན་རབ་གསལ་སྣང་བ།
  author: ས་བཟང་མ་ཏི་པཎ་ཆེན་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6623906699656229
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I1KG13713:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13713
      total_pages: 486
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13713.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6623906699656229
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
