id: P006899
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:29:31.955375
source_metadata:
  id: bdr:W22248
  title: སྤྱོད་འཇུག་རྣམ་བཤད་གཞུང་དོན་རབ་གསལ་སྣང་བ།
  author: ''
  volumes:
    f56e1e53c0db4a4bbe17ea331c3c7133:
      image_group_id: I1KG13713
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
